# Generated by Django 3.1.3 on 2021-11-25 16:38

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_resident', models.BooleanField(default=False)),
                ('is_official', models.BooleanField(default=False)),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('last_name', models.CharField(default='None', max_length=150)),
                ('first_name', models.CharField(default='None', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=6)),
                ('age', models.IntegerField(default='00')),
                ('birthday', models.DateField(blank=True, default='1111-11-11', null=True)),
                ('house_number', models.IntegerField(blank=True, default='00', null=True)),
                ('street', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='None', max_length=8, null=True)),
                ('religion', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('nationality', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('phone_number', models.IntegerField(blank=True, default='0000000000', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('last_name', models.CharField(default='None', max_length=150)),
                ('first_name', models.CharField(default='None', max_length=150)),
                ('middle_name', models.CharField(default='None', max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=6)),
                ('age', models.IntegerField(default='00')),
                ('birthday', models.DateField(default='1111-11-11')),
                ('house_number', models.IntegerField(default='00')),
                ('street', models.CharField(default='None', max_length=150)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='None', max_length=8)),
                ('religion', models.CharField(default='None', max_length=150)),
                ('nationality', models.CharField(default='None', max_length=150)),
                ('phone_number', models.IntegerField(blank=True, default='0000000000', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('last_name', models.CharField(default='None', max_length=150)),
                ('first_name', models.CharField(default='None', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=6)),
                ('age', models.IntegerField(default='00')),
                ('birthday', models.DateField(blank=True, default='1111-11-11', null=True)),
                ('house_number', models.IntegerField(blank=True, default='00', null=True)),
                ('street', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='None', max_length=8, null=True)),
                ('religion', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('nationality', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, default='None', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('image', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('last_name', models.CharField(default='None', max_length=150)),
                ('first_name', models.CharField(default='None', max_length=150)),
                ('middle_name', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='None', max_length=6)),
                ('age', models.IntegerField(default='00')),
                ('birthday', models.DateField(blank=True, default='1111-11-11', null=True)),
                ('house_number', models.IntegerField(blank=True, default='00', null=True)),
                ('street', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='None', max_length=8, null=True)),
                ('religion', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('nationality', models.CharField(blank=True, default='None', max_length=150, null=True)),
                ('phone_number', models.IntegerField(blank=True, default='0000000000', null=True)),
            ],
        ),
    ]
